import{a as L,i as n,S as b}from"./assets/vendor-B-D547pe.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&i(u)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const S="https://pixabay.com/api/",q="49829256-73c1564e94f64863eabbb2525";async function p(r,t=1,s=15){const i={key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:s,page:t};try{return(await L.get(S,{params:i})).data}catch{n.error({message:"Something went wrong. Please try again later."})}}const v=new b(".gallery a"),g=document.querySelector(".gallery");function M(){g.innerHTML=""}function y(r){const t=r.map(s=>`<li class="g-item">
        <a href="${s.largeImageURL}"><img class="g-img" src="${s.webformatURL}" alt="${s.tags}"></a>
        <ul class="g-list">
        <li class="g-list-item"><span class="text">Likes</span> <span class="num">${s.likes}</span></li>
        <li class="g-list-item"><span class="text">Views</span> <span class="num">${s.views}</span></li>
        <li class="g-list-item"><span class="text">Comments</span> <span class="num">${s.comments}</span></li>
        <li class="g-list-item"><span class="text">Downloads</span> <span class="num">${s.downloads}</span></li>
        </ul>
        </li>`).join("");g.insertAdjacentHTML("beforeend",t),v.refresh()}const x=document.querySelector(".form"),P=document.querySelector("input"),f=document.querySelector(".loader"),m=document.querySelector(".btn");let a=1;const c=15;let l="";function R(){f.style.display="flex"}function d(){f.style.display="none"}function E(){m.style.display="block"}function h(){m.style.display="none"}function w(){document.querySelector(".gallery").insertAdjacentHTML("afterend",`<p class="end-message">We're sorry, but you've reached the end of search results.</p>`)}function H(){const r=document.querySelector(".end-message");r&&r.remove()}x.addEventListener("submit",async r=>{if(r.preventDefault(),R(),l=P.value.trim(),a=1,H(),!l){n.warning({message:"Please, enter a search query",color:"yellow",position:"topRight"}),d();return}try{const t=await p(l,a,c);if(t.hits.length===0){n.warning({message:"Sorry, there are no images matching your search query. Please try again!",color:"yellow",position:"topRight"});return}M(),y(t.hits),E(),t.hits.length<c&&(h(),w())}catch{n.error({message:"Something went wrong :(",position:"topRight"})}finally{d()}});m.addEventListener("click",async r=>{r.preventDefault(),a+=1;try{const t=await p(l,a,c);y(t.hits);const{height:s}=document.querySelector(".gallery li").getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"}),a*c>=t.totalHits&&(h(),document.querySelector(".end-message")||w())}catch{n.error({message:"Failed to load more images.",position:"topRight"})}finally{d()}});
//# sourceMappingURL=index.js.map
